### ISSUE TITLE
SIGQUIT when running with -bench=.

### ISSUE THREAD

**Issue by jbuberel** [julienschmidt/go-http-routing-benchmark#44]
Here's a problem I've now run into consistently running the benchmarks using go 1.4.2 and 1.5 (master):

http://pastebin.com/K1QweDns

The SIGQUIT occurs in different places each time, although the stack dumps often mention Beego. 

Significantly, these problems were only seen using virtualized Linux instances (VMWare, VirtualBox). Have you seen similar stack dumps running the full suite?

**Comment by julienschmidt** [comment]
It is quite unusual for an program to send SIGQUIT. AFAIK this signal is usually manually triggered by the user.

If it always happens after roughly the same run time, my best guess would be that it is triggered by `go test`s timeout. You can set a higher timeout with e.g. `go test -timeout=2h -bench=.`.
But you should see a more helpful explanation in that case.

**Comment by jbuberel** [comment]
Let me give that a try!

**Comment by jbuberel** [comment]
Yep - that was it. Just a overall timeout problem. Thanks for the tip.
