### ISSUE TITLE
Macaron?

### ISSUE THREAD

**Issue by KempWatson** [julienschmidt/go-http-routing-benchmark#64]
Hi, Macaron seems to be a popular framework,
perhaps you could add that to this great resource?
Thanks!

**Comment by TamalSaha** [comment]
I am also interested in numbers for Macaron. I saw that there are code for Macaron in tests.

**Comment by julienschmidt** [comment]
Tests for Macaron are already implemented. The results will be included in the next round. You can run the benchmark on your own if desired.
