### ISSUE TITLE
Please consider vendor or regular dependency updates

### ISSUE THREAD

**Issue by tendervittles** [julienschmidt/go-http-routing-benchmark#70]
I'm trying to run benchmarks from the last commit (2b136956a56bc65dddfa4bdaf7d1728ae2c90d50).

Using Go 1.8 and all fresh dependencies, I'm seeing lots of build problems.

* The project github.com/Unknwon/macaron doesn't build. That repo is deprecated and now located at github.com/go-macaron/macaron.
* The latest echo package has signature changes.
* The latest gojiv2 also has other problems.

Ideally, a process would regularly update all dependencies to ensure that everything still works.

Barring that, capturing the current dependencies in vendor would allow me to recreate your exact setup.

Regular updates that are captured in vendor would be sweet.

**Comment by julienschmidt** [comment]
Fixed by 052672f2944d5f4205b707a55ab1764ffa321f23

Go modules are used now. However, this still requires manual dependency updates.
