### ISSUE TITLE
Benchmark against native Go http.HandleFunc

### ISSUE THREAD

**Issue by Commenter123** [julienschmidt/go-http-routing-benchmark#76]
Hi. Please include the native Go http.HandleFunc in your benchmarks. I know it lacks a lot of features but it would be cool to see how httprouter compares against it. Thank you

**Comment by julienschmidt** [comment]
If you mean the http.DefaultServeMux / http.ServeMux: It has been there from the start under the name "HttpServeMux". Due to its limited capabilities, it is only included in the static benchmark.
